name: Github - mirroring - GCP - Tags

on:
  workflow_run:
    workflows: ["Github - mirroring - GCP - Prd"]
    branches: [main]
    types:
      - completed

jobs:
  check_tag:
    runs-on: ubuntu-latest
    outputs:
      is_tag: ${{ steps.tag_check.outputs.is_tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: '20'
      - name: Check for Tag
        id: tag_check
        run: |
          git show-ref --tags

  deploy:
    needs: check_tag
    if: needs.check_tag.outputs.is_tag == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy Project
        run: echo "Deploying because this was triggered by a tag."
