name: Github - mirroring - GCP - Tags

on:
  workflow_run:
    workflows: ["Github - mirroring - GCP - Prd"]
    branches: [main]
    types:
      - completed

jobs:
  check_tag:
    runs-on: ubuntu-latest
    outputs:
      is_tag: ${{ steps.tag_check.outputs.is_tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 20
          fetch-tags: true
      - name: Check for Tag
        id: tag_check
        run: |
          TAG_NAME=$(git tag --points-at ${{ github.event.workflow_run.head_commit.id }} | head -n 1)
          if [[ -z "$TAG_NAME" ]]; then
            echo "This is not a tag push."
            echo "is_tag=false" >> $GITHUB_OUTPUT
          else
            echo "This workflow was triggered by a tag: $TAG_NAME"
            echo "is_tag=true" >> $GITHUB_OUTPUT
            echo "::set-output name=tag_name::$TAG_NAME"
          fi

  tagging_remote:
    needs: check_tag
    if: needs.check_tag.outputs.is_tag == 'true'
    runs-on: ubuntu-latest
    environment: prd
    permissions:
      contents: read
      id-token: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
